name: Cosmic Money CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Just
        run: |
          sudo apt-get update && sudo apt-get install -y just

      - name: Install Dependencies
        run: |
          sudo apt-get install -y libgtk-3-dev libsoup2.4-dev flatpak flatpak-builder python3-pip
          pip3 install --user flatpak-cargo-generator

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build Debug
        run: |
          just build-debug

      - name: Run Clippy for Linting
        run: |
          just check

      - name: Build Release
        run: |
          just build-release

      - name: Install SDK for Flatpak
        run: |
          just install-sdk

      - name: Generate Flatpak Sources
        run: |
          just sources-gen

      - name: Package Flatpak
        run: |
          just package-flatpak
        env:
          FLATPAK_ENABLE_SDK_EXT: "rust-stable,llvm18"

      - name: Upload Flatpak Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cosmic_money_flatpak
          path: repo/com.francescogaglione.cosmicmoney.flatpak

      - name: Build Debian Package
        run: |
          just debpkg

      - name: Upload Debian Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cosmic_money_deb
          path: target/debian/*.deb

      - name: Clean Up
        run: |
          just clean-dist